##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.6.0-B36] date: [Sun Apr 20 21:22:53 PDT 2025]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32wb55_color


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/my_tasks.c \
Core/Src/app_freertos.c \
Core/Src/stm32wbxx_it.c \
Core/Src/stm32wbxx_hal_msp.c \
Core/Src/stm32wbxx_hal_timebase_tim.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_hsem.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_exti.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c \
Core/Src/system_stm32wbxx.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Drivers/CubeMxDriver/clock/system_clock_config.c \
Drivers/CubeMxDriver/i2c/i2c_init.c \
Drivers/CubeMxDriver/rf/rf_init.c \
Drivers/CubeMxDriver/spi/spi_init.c \
Drivers/CubeMxDriver/tim/tim_init.c \
Drivers/CubeMxDriver/gpio/gpio__init.c \
Drivers/CubeMxDriver/system/error_handler.c \
Drivers/CubeMxDriver/system/tick_callback.c \
Drivers/CubeMxDriver/usart/usart_init.c \
Drivers/MyDriver/stepper__driver.c \
Drivers/MyDriver/drv8833__driver.c \
Drivers/MyDriver/led__driver.c \
Services/motor__control.c \
Services/sensor__manager.c \
Services/ble__service.c \
Services/led__controller.c \
Services/mixing__algorithm.c \
Services/power__manager.c \
Services/error__manager.c \
Services/logger__service.c \
App/app__main.c \
App/blink__logic.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci/shci.c \
Middlewares/ST/STM32_WPAN/utilities/stm_list.c \
Middlewares/ST/STM32_WPAN/utilities/stm_queue.c \
Middlewares/ST/STM32_WPAN/utilities/stm32_mm.c \
Middlewares/ST/STM32_WPAN/utilities/dbg_trace.c \
Core/Src/hw_ipcc.c \
Core/Src/ble_user_callbacks.c \
Core/Src/ble_aci_stubs.c



# ASM sources
ASM_SOURCES =  \
startup_stm32wb55xx_cm4.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32WB55xx \
-DSTM32_WPAN_ENABLED


# AS includes
AS_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32WBxx_HAL_Driver/Inc \
-IDrivers/STM32WBxx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/Device/ST/STM32WBxx/Include \
-IDrivers/CMSIS/Include

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32WBxx_HAL_Driver/Inc \
-IDrivers/STM32WBxx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/Device/ST/STM32WBxx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/CubeMxDriver \
-IDrivers/CubeMxDriver/clock \
-IDrivers/CubeMxDriver/gpio \
-IDrivers/CubeMxDriver/i2c \
-IDrivers/CubeMxDriver/tim \
-IDrivers/CubeMxDriver/rf \
-IDrivers/CubeMxDriver/spi \
-IDrivers/CubeMxDriver/system \
-IDrivers/CubeMxDriver/usart \
-IDrivers/MyDriver \
-IServices \
-IUtils \
-ITests \
-IApp \
-IMiddlewares/ST/STM32_WPAN/ble \
-IMiddlewares/ST/STM32_WPAN/ble/core \
-IMiddlewares/ST/STM32_WPAN/ble/core/auto \
-IMiddlewares/ST/STM32_WPAN/ble/core/template \
-IMiddlewares/ST/STM32_WPAN/ble/svc/Inc \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci \
-IMiddlewares/ST/STM32_WPAN/utilities





# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32wb55xx_flash_cm4.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

#vpath %.c Core/Src Drivers/STM32WBxx_HAL_Driver/Src Middlewares/Third_Party/FreeRTOS/Source Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 MyDriver/clock

# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# flash targets
#######################################
# Flash with J-Link (Primary method)
flash: $(BUILD_DIR)/$(TARGET).hex
	@echo "Flashing $(TARGET) with J-Link..."
	JLinkExe -device STM32WB55CG -if SWD -speed 4000 -autoconnect 1 -CommanderScript flash.jlink

# Flash with J-Link using hex file
flash-jlink: $(BUILD_DIR)/$(TARGET).hex
	@echo "Flashing $(TARGET) with J-Link..."
	@echo "Creating J-Link script..."
	@echo "r" > flash_jlink.jlink
	@echo "loadfile $(BUILD_DIR)/$(TARGET).hex" >> flash_jlink.jlink
	@echo "r" >> flash_jlink.jlink
	@echo "go" >> flash_jlink.jlink
	@echo "exit" >> flash_jlink.jlink
	JLinkExe -device STM32WB55CG -if SWD -speed 4000 -autoconnect 1 -CommanderScript flash_jlink.jlink
	@rm -f flash_jlink.jlink

# Flash with J-Link using binary file
flash-jlink-bin: $(BUILD_DIR)/$(TARGET).bin
	@echo "Flashing $(TARGET) binary with J-Link..."
	@echo "Creating J-Link script..."
	@echo "r" > flash_jlink_bin.jlink
	@echo "loadbin $(BUILD_DIR)/$(TARGET).bin, 0x08000000" >> flash_jlink_bin.jlink
	@echo "r" >> flash_jlink_bin.jlink
	@echo "go" >> flash_jlink_bin.jlink
	@echo "exit" >> flash_jlink_bin.jlink
	JLinkExe -device STM32WB55CG -if SWD -speed 4000 -autoconnect 1 -CommanderScript flash_jlink_bin.jlink
	@rm -f flash_jlink_bin.jlink

# Flash with STM32CubeProgrammer (alternative)
flash-cube: $(BUILD_DIR)/$(TARGET).hex
	@echo "Flashing $(TARGET) with STM32CubeProgrammer..."
	STM32_Programmer_CLI -c port=SWD -d $(BUILD_DIR)/$(TARGET).hex -rst

# Flash with OpenOCD + J-Link
flash-openocd: $(BUILD_DIR)/$(TARGET).hex
	@echo "Flashing $(TARGET) with OpenOCD + J-Link..."
	openocd -f interface/jlink.cfg -f target/stm32wbx.cfg -c "program $(BUILD_DIR)/$(TARGET).hex verify reset exit"

# Erase flash with J-Link
erase:
	@echo "Erasing STM32 flash with J-Link..."
	@echo "r" > erase_jlink.jlink
	@echo "erase" >> erase_jlink.jlink
	@echo "exit" >> erase_jlink.jlink
	JLinkExe -device STM32WB55CG -if SWD -speed 4000 -autoconnect 1 -CommanderScript erase_jlink.jlink
	@rm -f erase_jlink.jlink

# Erase flash with STM32CubeProgrammer
erase-cube:
	@echo "Erasing STM32 flash with STM32CubeProgrammer..."
	STM32_Programmer_CLI -c port=SWD -e all

# Start J-Link GDB Server for debugging
debug-server:
	@echo "Starting J-Link GDB Server..."
	@echo "J-Link GDB Server will run on port 2331"
	JLinkGDBServer -device STM32WB55CG -if SWD -speed 4000 -port 2331 -singlerun -nogui

# Connect with GDB (run in another terminal after debug-server)
debug-gdb: $(BUILD_DIR)/$(TARGET).elf
	@echo "Connecting with GDB..."
	@echo "Make sure J-Link GDB Server is running (make debug-server)"
	@echo "Commands to use in GDB:"
	@echo "  target remote localhost:2331"
	@echo "  load"
	@echo "  monitor reset"
	@echo "  continue"
	arm-none-eabi-gdb $(BUILD_DIR)/$(TARGET).elf

# Start J-Link RTT Viewer for real-time debugging
debug-rtt:
	@echo "Starting J-Link RTT Viewer..."
	JLinkRTTViewer

# Flash wireless stack (needs to be downloaded separately)
flash-wireless:
	@echo "Flash the wireless stack using J-Link:"
	@echo "JLinkExe -device STM32WB55CG -if SWD -speed 4000"
	@echo "Then in J-Link: loadbin stm32wb5x_BLE_Stack_light_fw.bin,0x080CB000"
	@echo "Download wireless stack from: https://www.st.com/en/embedded-software/stm32cubewb.html"

# Show help
flash-help:
	@echo "Available flash targets:"
	@echo "  flash           - Flash application with J-Link"
	@echo "  flash-jlink     - Flash application with J-Link (dynamic script)"
	@echo "  flash-jlink-bin - Flash binary with J-Link"
	@echo "  flash-cube      - Flash application with STM32CubeProgrammer"
	@echo "  flash-openocd   - Flash application with OpenOCD + J-Link"
	@echo "  erase           - Erase entire flash with J-Link"
	@echo "  erase-cube      - Erase entire flash with STM32CubeProgrammer"
	@echo "  debug-server    - Start J-Link GDB Server"
	@echo "  debug-gdb       - Connect GDB to J-Link"
	@echo "  debug-rtt       - Start J-Link RTT Viewer"
	@echo "  flash-wireless  - Instructions for flashing wireless stack"
	@echo "  flash-help      - Show this help"

.PHONY: flash flash-jlink flash-jlink-bin flash-cube flash-openocd erase erase-cube debug-server debug-gdb debug-rtt flash-wireless flash-help
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***